export const pics = [aliayh-mamaw-pool.png, aliyah-blue-castle.png, aliyah-dragon2.png,
aliyah-dragon.png, aliyah-front-windows2.png, aliyah-front-windows.png,
aliyah-inride.png, aliyah-mamaw-inride2.png, aliyah-mamaw-inride.png,
aliyah-mamaw-kelsey-bus.png, aliyah-mamaw-pool-wave.mov,
aliyah-mamaw-pool-wave.mp4, aliyah-mamaw-ride-wave.png,
aliyah-mamaw-wave-ride2.png, aliyah-mam-pool2.png, aliyah-mam-pool3.png,
aliyah-mam-pool-small.png, aliyah-poolside2.png, aliyah-poolside.png,
aliyah-pool-sip.png, aliyah-spinwheel.png, aliyah-tev-castle-alt2.png,
aliyah-tev-castle-alt3.png, aliyah-tev-castle-alt.png,
aliyah-tev-crossroads.png, aliyah-tev-ride.png, aliyah-tev-springfield2.png,
aliyah-tev-springfield.png, aliyah-tev-tiedye2.png, aliyah-tev-tiedye.png,
aliyah-tev-tower.png, aliyah-tev-train-mmug.png, aliyah-wand-instructions.png,
aliyah-wand.png, family-restraunt.png, GoodSpin.mov, GoodSpin.mp4, pic.txt,
tev-wave-ride-small.png]
